repos:
  - repo: local
    hooks:
      - id: go-test
        name: Run Go tests
        entry: go test ./...
        language: system
        pass_filenames: false

      - id: go-fmt
        name: Run Go format
        entry: go fmt ./...
        language: system
        pass_filenames: false

      - id: go-build
        name: Build go binary
        entry: go build
        language: system
        pass_filenames: false
